read_format = "real"
virt_obj_scale_factor = 0.5
virtual_distance_to_m = 1000
virtual_obj_depth_in_meters = 0.45
color_black_threshold = 10
epsilon = 1e-5
distance_constant_val = 2
color_histogram_bins = 180
max_hue_value = 180
color_weight = 0.5
cost_method = "single"
automatic_threshold = 0.05
closing_kernel_size = (5, 5)
guided_window_radius = 8
guided_regulization = 0.05
trimap_size = 5
num_erosion = 3
canny_lower_bound = 50
canny_upper_bound = 150
dilation_kernel_size = (5, 5)
alpha_neighbors =  [15, 10]
alpha_max_iter = 50000
gaussian_blur_kernel = (5, 5)